B/testing setup
julklingel/Hofmarkt pull request #42
Opened 2023-03-14 15:47 UTC by juro95

Hab hier mal das Test setup eingerichtet mit pactum. Musste auch direkt ein paar Sachen ändern die beim testen sonst nicht funktioniert haben.

2023-03-14 16:39 UTC, julklingel requested changes

2023-03-14 16:39 UTC, julklingel commented on backend/.env.test
> +JWT_secret="secret-yo"
Ich glaube ich würde hier ein env.example erstellen und die test variablen im richtigen env als variablen eintragen. So wie damals bei Crac. Was meinst du?

2023-03-14 16:39 UTC, julklingel commented on backend/pnpm-lock.yaml
Wir sollten das backend/pnpm-lock.yaml auch in Git Ignore packen.

2023-03-14 16:39 UTC, julklingel commented on backend/src/db-module/prisma.service.ts
> +    ]);
Ich vertrau dir hier mal. Keine Ahnung ob das passt. Aber du bist ja ein Pro-backend dev.

2023-03-14 16:39 UTC, julklingel commented on backend/test/app.e2e-spec.ts
> +    await app.close();
Müsste man nicht hier auch die DB clearen? Das ist doch nicht in der app.close() function mit drinnen?

2023-03-14 16:39 UTC, julklingel commented on backend/test/app.e2e-spec.ts
Die Tests sind eigentlich Integration Test weil damit nicht das Frontend getestet wird. Du schießt req. gegen die APIs aber das Frontend bleibt unberührt. --> Daher würde ich das File umbenennen.

2023-03-14 16:39 UTC, julklingel commented on backend/test/app.e2e-spec.ts
> +describe('App e2e test', () => {
Same here, Integration test

2023-03-17 15:54 UTC, juro95 commented on backend/.env.test
> +JWT_secret="secret-yo"
Das ist ja nur dafür da das der test server auf 5435 statt 5432 läuft oder wie meinst du das?

2023-03-17 16:01 UTC, juro95 commented on backend/src/db-module/prisma.service.ts
> +    ]);
das war auch von flad, die funktion wird nur immer vor den tests  aufgerufen damit die test credentials noch nicht in der db sind.

2023-03-17 16:02 UTC, juro95 commented on backend/test/app.e2e-spec.ts
> +    await app.close();
Denke nicht weil es ja schon immer am anfang gecleared wird

2023-03-17 18:06 UTC, julklingel commented on backend/.env.test
> +JWT_secret="secret-yo"
Jup, aber ich würde alles in ein env file packen und kein eigenes env file für testing erstellen.

2023-03-17 18:11 UTC, julklingel commented on backend/test/app.e2e-spec.ts
> +    await app.close();
Ok passt.

2023-03-20 14:35 UTC, juro95 commented
habs noch nicht hinbekommen die tests nur aus einem .env file laufen zu lassen
Ich muss nachher mal taka fragen

2023-03-20 15:34 UTC, julklingel approved these changes

2023-03-20 15:51 UTC, merged